# -*- coding: utf-8 -*-
"""Knwldge Disc. & Data Mining Final Project (Goose)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13WeFM6w8CpNoBFafQ8SDD4o8ZGchWgLQ

##  **Clone the  YOLOv10 Github Repository**
"""



!pip install git+https://github.com/THU-MIG/yolov10.git
!pip install roboflow

"""## **Download YOLOv10 pre-trained weights**"""

from google.colab import drive
drive.mount('/content/drive') # mount google folder under content folder

!ls ~/ # list the files and folders under root folder.
!pwd # you are always under content folder

!wget -P ./drive/MyDrive/yolov10/weights/ https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10n.pt

"""## **Download dataset from Roboflow Universe**"""

from roboflow import Roboflow
rf = Roboflow(api_key="BwSN7tr7HJYr0g2Ehhmz")
project = rf.workspace("dothanhchien").project("fire-k6xeb-w7kq7")
version = project.version(1)
dataset = version.download("yolov8")

"""## **Move the dataset to my GoogleDrive.**"""

# Make sure it pulls from dataset the GetYourGoose6.v6i.yolov8 that was uploaded to my google drive

!mv ./Fire-1 ./drive/MyDrive/GetYourGoose6.v6i.yolov8

"""## **Start the Training**"""

# int value to automatically select "Don't output results", click 3 when prompted.
choice = 3

# @title Default title text
!yolo task=detect mode=train epochs=100 batch=32 plots=True
model='/content/drive/MyDrive/yolov10/weights/yolov10n.pt'
data='./drive/MyDrive/GetYourGoose6.v6i.yolov8/data.yaml'

"""#**Display the confusion matrix and Results**"""

from IPython.display import Image
from ultralytics import YOLOv10

Image(filename='/content/runs/detect/train3/confusion_matrix.png', width=800)

Image(filename='/content/runs/detect/train3/results.png', width=600)

"""# **Testing the Trained Model**

**Test one image**
"""

#A new predict file is created each time the programs is ran in that session
model_path = '/content/runs/detect/train3/weights/best.pt'
model = YOLOv10(model_path)
results = model(source='./drive/MyDrive/GetYourGoose6.v6i.yolov8/test/images', conf=0.25,save=True)

from google.colab import drive
drive.mount('/content/drive')

"""**Test images from a folder named predict4**"""

#Results saved to runs/detect/predict

import glob
images = glob.glob('/content/runs/detect/predict/image3_jpg.rf.921d44fb38891c670d939b756a51972b.jpg') # you have to use the correct extension here, e.g. png, jpg, jpeg, and so on.
for image in images:
  display(Image(filename = image,width=400))

"""# **Testing on a video file**"""

#Commented out because it's not necessary
'''
model_path = '/content/runs/detect/train2/weights/best.pt'
model = YOLOv10(model_path)
results = model(source='/content/drive/MyDrive/yolov10/testvideo.mov', conf=0.25,save=True)
'''